const initialState = {
  restaurantId: "0",
  reviews: [
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 101,
      "user_initials": "VF",
      "user_name": "Vivien Farrell",
      "user_location": "Louvain-la-Neuve",
      "user_review_count": 36,
      "dine_date": "2018-08-19 11:09:28",
      "rating_overall": 4,
      "rating_food": 3,
      "rating_service": 4,
      "rating_ambience": 4,
      "helpful_count": 23,
      "body": "consequat"
    },
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 102,
      "user_initials": "HC",
      "user_name": "Hamilton Cotton",
      "user_location": "Massenhoven",
      "user_review_count": 18,
      "dine_date": "2017-08-20 16:31:17",
      "rating_overall": 3,
      "rating_food": 1,
      "rating_service": 5,
      "rating_ambience": 4,
      "helpful_count": 74,
      "body": "nisi sem semper erat, in"
    },
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 103,
      "user_initials": "HC",
      "user_name": "Hamilton Cotton",
      "user_location": "Massenhoven",
      "user_review_count": 18,
      "dine_date": "2019-01-20 16:31:17",
      "rating_overall": 3,
      "rating_food": 1,
      "rating_service": 5,
      "rating_ambience": 4,
      "helpful_count": 74,
      "body": "nisi sem semper erat, in"
    },
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 104,
      "user_initials": "HC",
      "user_name": "Hamilton Cotton",
      "user_location": "Massenhoven",
      "user_review_count": 18,
      "dine_date": "2019-02-20 16:31:17",
      "rating_overall": 3,
      "rating_food": 1,
      "rating_service": 5,
      "rating_ambience": 4,
      "helpful_count": 74,
      "body": "nisi sem semper erat, in"
    },
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 105,
      "user_initials": "HC",
      "user_name": "Hamilton Cotton",
      "user_location": "Massenhoven",
      "user_review_count": 18,
      "dine_date": "2019-03-20 16:31:17",
      "rating_overall": 3,
      "rating_food": 1,
      "rating_service": 5,
      "rating_ambience": 4,
      "helpful_count": 74,
      "body": "nisi sem semper erat, in"
    },
    {
      "restaurant_id": "0",
      "restaurant_name": "#1 Restaurant Name",
      "review_id": 106,
      "user_initials": "VF",
      "user_name": "Vivien Farrell",
      "user_location": "Louvain-la-Neuve",
      "user_review_count": 36,
      "dine_date": "2018-04-19 11:09:28",
      "rating_overall": 4,
      "rating_food": 3,
      "rating_service": 4,
      "rating_ambience": 4,
      "helpful_count": 23,
      "body": "consequat",
    },
  ],
  summary: {
    "restaurant_id": "0",
    "reviewersCount": 2,
    "reviewsCount": 6,
    "overallRatings": {
      "food": 2,
      "service": 4.5,
      "ambience": 4,
      "value": 3.5,
    },
    "ratingFrequencies": {
      "5": 5,
      "4": 1,
    },
  },
}

export default initialState;
